# Generated by Django 4.2.2 on 2024-03-05 05:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('top', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(max_length=100)),
                ('diary_content', models.TextField()),
                ('diary_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('diary_spoiler', models.BooleanField(default=False)),
                ('diary_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('diary_tag', models.ManyToManyField(to='top.tag')),
                ('diary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_image_image', models.ImageField(upload_to='media/')),
                ('diary_image_comment', models.CharField(max_length=100)),
                ('diary_image_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_comment_comment', models.CharField(max_length=1000)),
                ('diary_comment_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
                ('diary_comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
