# Generated by Django 4.2.2 on 2024-03-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('-id',)},
        ),
    ]
