# Generated by Django 4.2.2 on 2024-03-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryimage',
            name='diary_image_mainflag',
            field=models.BooleanField(default=False),
        ),
    ]
