# Generated by Django 4.2.2 on 2024-03-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diaryimage_diary_image_mainflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='diary_image_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
