# Generated by Django 4.2.2 on 2024-03-05 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('top', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('game_content', models.TextField()),
                ('game_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('game_tag', models.ManyToManyField(to='top.tag')),
            ],
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_comment_comment', models.CharField(max_length=1000)),
                ('game_comment_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('game_comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
